name: Build FlameRobin for Debian

env:
  wx-tag-version: v3.2.6
  flamerobin-version: 0.9.13 

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    # Installing required dependencies
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential cmake libwxgtk3.2-dev dpkg-dev libfbclient2 libtool-bin firebird3.0-server firebird3.0-utils 
        
    # Cache wxWidgets if already built
    - name: wxWidget cache
      id: cache-wxwidget
      uses: actions/cache@v4
      with:
        path: wxWidgets
        key: ${{ runner.os }}-wxwidgets-${{env.wx-tag-version}}
        restore-keys: ${{ runner.os }}-wxwidgets-${{env.wx-tag-version}}

    # Clone and compile wxWidgets if not already cached
    - if: ${{ steps.cache-wxwidget.outputs.cache-hit != 'true' }}
      name: Clone wxWidgets
      run: git clone --recursive --branch ${{ env.wx-tag-version }} --depth 1 https://github.com/wxWidgets/wxWidgets.git

    - if: ${{ steps.cache-wxwidget.outputs.cache-hit != 'true' }}
      name: Build wxWidgets
      run: |
        cd wxWidgets
        mkdir build && cd build
        cmake .. -DwxBUILD_SHARED=OFF -DCMAKE_BUILD_TYPE=Release
        make -j $(nproc)
        sudo make install
        sudo ldconfig

    # Building the CMake project for Flamerobin
    - name: Generate CMake project
      run: cmake -S . -B Build -DSTATIC_BUILD=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local

    # FlameRobin Compilation
    - name: Build Flamerobin
      run: cmake --build Build --config Release -j$(nproc)

    # Check where the generated binary is
    - name: Find compiled executable
      run: find Build/ -type f -executable

    # Copy the executable into the package (adjust the path if necessary)
    - name: Copy compiled binary into package
      run: cp -r Build/flamerobin flamerobin/templates/trees/deb/flamerobin/usr/local/bin

    # Generate the .deb file
    - name: Build .deb package
      run: |
        dpkg-deb --build flamerobin/templates/trees/deb/flamerobin flamerobin/templates/trees/deb/flamerobin-${{ env.flamerobin-version }}.deb

    # Uploading the installer as a GitHub Actions artifact
    - name: Upload .deb package
      uses: actions/upload-artifact@v4
      with:
        name: flamerobin-deb
        path: flamerobin/templates/trees/deb/flamerobin-${{ env.flamerobin-version }}.deb
